### ISSUE TITLE
Question regarding loginService.user object

### ISSUE THREAD

**Issue by sheldonwjones** [mrgamer/angular-login-example#12]
I've got a service that needs to access the user object stored in login service. Is there a way to wait for the user object to become ready?

```javascript
angular.module('apiService', [])
    .factory('apiService', function (loginService) {
        console.log(loginService.user);
   });
```

This returns {} in the console log. I think I can use localstorage, but I'm sure I'm missing something.

Thanks

**Comment by mrgamer** [comment]
timeout exceeded, closing!
