### ISSUE TITLE
privacy maybe?

### ISSUE THREAD

**Issue by seminice** [mrgamer/angular-login-example#22]
Before showing email addresses in public like that after someone registers in the example, Can you at least set a small warning about that "Your emaill address and login credentials will be shared to the public" ?
If you can please remove our credentials from the homepage.
Thanks in advanced.

**Comment by colthreepv** [comment]
The [message in the register page](https://github.com/mrgamer/angular-login-example/blob/master/src/register/register.tpl.html#L4) is not false.
The data you put in the registration only gets written in **YOUR** localStorage, so only **YOU** can see it.

Just open the website in private browsing to check that by yourself.

**Comment by seminice** [comment]
Sorry , used to see John doe and Jane Doe and @example.com email addresses, yours seemed real at the first glance haha .. sorry again.
