### ISSUE TITLE
All files included?

### ISSUE THREAD

**Issue by nittanycolonial** [mrgamer/angular-login-example#25]
Are all the files included in the git downloads? I have tried downloading the zip and via git but there still seems to be files missing from the archive. Just as an example, templates-app.js is missing from the zip archive and I have a feeling there may be others missing.

**Comment by a6kme** [comment]
Yes. Many other files are also missing. libs.js, style.css to name a few.

**Comment by colthreepv** [comment]
Please refer to: [https://github.com/mrgamer/angular-login-example#start-the-project-locally](How to start project locally)

`libs.js` and `style.css` are files generated by Grunt build system
